name: "nix-develop-command"
description: "Run commands in a nix develop environment"

inputs:
  command:
    description: "The command to run"
    required: true
  devshell:
    description: "Name of the development shell"
    default: "default"
  options:
    description: "Additional options/arguments for nix develop"
    default: ""
  working-directory:
    description: "Working directory"
    default: "./"

runs:
  using: "composite"
  steps:
    - run: ${{ inputs.command }}
      shell: nix develop .#${{ inputs.devshell }} ${{ inputs.options }} --command bash {0}
      working-directory: ${{ inputs.working-directory }}
